name: phpldapadmin
services:
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    restart: unless-stopped
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=samba-ad-dc
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8080:80"
    networks:
      backend:
        mac_address: 52:54:00:02:83:02   # Mini PC #1, Backend VLAN, slot 2
      services:
        mac_address: 52:54:00:02:23:02   # Mini PC #1, Services VLAN, slot 2

networks:
  backend:
    external: true
  services:
    external: true

x-casaos:
  architectures: [amd64]
  main: phpldapadmin
  category: Identity
  description:
    en_US: Web-based LDAP administration tool for Samba AD DC.
  icon: ./icon.png
  screenshots:
    - ./screenshot-1.png
  title:
    en_US: phpLDAPadmin
  tagline:
    en_US: Lightweight LDAP tree browser and editor.
